#!/bin/sh
wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
java -jar BuildTools.jar
java -jar fernflower.jar -dgs=true spigot-*.jar out
cd out
unzip spigot*.jar
rm spigot*.jar
cd ..
mv out src
rm BuildTools.jar
printf "Spigot's sources are available in the src folder\n"

